/*
 * Qompose - A simple programmer's text editor.
 * Copyright (C)Axel Rasmussen
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either versionof the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "Utils.h"

namespace qompose
{
namespace spelling_utils
{
/*!
 * This function returns the ISO-1 language code for the given QLocale's
 * language() property. If the language property value is not supported, then
 * a default-constructed QString will be returned instead.
 *
 * For more information, see:
 *
 *     https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
 *
 * \param locale The locale object to inspect.
 * \return The ISO-1 language code for the locale's language.
 */
QString getLocaleLanguageCode(const QLocale &locale)
{
	switch(locale.language())
	{
	case QLocale::Language::Abkhazian:
		return "ab";
	case QLocale::Language::Afar:
		return "aa";
	case QLocale::Language::Afrikaans:
		return "af";
	case QLocale::Language::Albanian:
		return "sq";
	case QLocale::Language::Amharic:
		return "am";
	case QLocale::Language::Arabic:
		return "ar";
	case QLocale::Language::Armenian:
		return "hy";
	case QLocale::Language::Assamese:
		return "as";
	case QLocale::Language::Aymara:
		return "ay";
	case QLocale::Language::Azerbaijani:
		return "az";
	case QLocale::Language::Bashkir:
		return "ba";
	case QLocale::Language::Basque:
		return "eu";
	case QLocale::Language::Bengali:
		return "bn";
	case QLocale::Language::Bihari:
		return "bh";
	case QLocale::Language::Bislama:
		return "bi";
	case QLocale::Language::Bosnian:
		return "bs";
	case QLocale::Language::Breton:
		return "br";
	case QLocale::Language::Bulgarian:
		return "bg";
	case QLocale::Language::Burmese:
		return "my";
	case QLocale::Language::Catalan:
		return "ca";
	case QLocale::Language::Chinese:
		return "zh";
	case QLocale::Language::Cornish:
		return "kw";
	case QLocale::Language::Corsican:
		return "co";
	case QLocale::Language::Croatian:
		return "hr";
	case QLocale::Language::Czech:
		return "cs";
	case QLocale::Language::Danish:
		return "da";
	case QLocale::Language::Divehi:
		return "dv";
	case QLocale::Language::Dutch:
		return "nl";

	case QLocale::Language::AnyLanguage:
	case QLocale::Language::C:
	case QLocale::Language::English:
		return "en";

	case QLocale::Language::Esperanto:
		return "eo";
	case QLocale::Language::Estonian:
		return "et";
	case QLocale::Language::Faroese:
		return "fo";
	case QLocale::Language::Finnish:
		return "fi";
	case QLocale::Language::French:
		return "fr";
	case QLocale::Language::Gaelic:
		return "gd";
	case QLocale::Language::Galician:
		return "gl";
	case QLocale::Language::Georgian:
		return "ka";

	case QLocale::Language::LowGerman:
	case QLocale::Language::SwissGerman:
	case QLocale::Language::German:
		return "de";

	case QLocale::Language::Greek:
		return "el";
	case QLocale::Language::Guarani:
		return "gn";
	case QLocale::Language::Gujarati:
		return "gu";
	case QLocale::Language::Hausa:
		return "ha";
	case QLocale::Language::Hebrew:
		return "he";
	case QLocale::Language::Hindi:
		return "hi";
	case QLocale::Language::Hungarian:
		return "hu";
	case QLocale::Language::Icelandic:
		return "is";
	case QLocale::Language::Indonesian:
		return "id";
	case QLocale::Language::Interlingua:
		return "ia";
	case QLocale::Language::Interlingue:
		return "ie";
	case QLocale::Language::Inupiak:
		return "ik";
	case QLocale::Language::Irish:
		return "ga";
	case QLocale::Language::Italian:
		return "it";
	case QLocale::Language::Japanese:
		return "ja";
	case QLocale::Language::Javanese:
		return "jv";
	case QLocale::Language::Kannada:
		return "kn";
	case QLocale::Language::Kashmiri:
		return "ks";
	case QLocale::Language::Kazakh:
		return "kk";
	case QLocale::Language::Kinyarwanda:
		return "rw";
	case QLocale::Language::Kirghiz:
		return "ky";
	case QLocale::Language::Korean:
		return "ko";
	case QLocale::Language::Kurdish:
		return "ku";
	case QLocale::Language::Latvian:
		return "lv";
	case QLocale::Language::Lingala:
		return "ln";
	case QLocale::Language::Lithuanian:
		return "lt";
	case QLocale::Language::Macedonian:
		return "mk";
	case QLocale::Language::Malagasy:
		return "mg";
	case QLocale::Language::Malay:
		return "ms";
	case QLocale::Language::Malayalam:
		return "ml";
	case QLocale::Language::Maltese:
		return "mt";
	case QLocale::Language::Maori:
		return "mi";
	case QLocale::Language::Marathi:
		return "mr";
	case QLocale::Language::Mongolian:
		return "mn";
	case QLocale::Language::NauruLanguage:
		return "na";
	case QLocale::Language::Nepali:
		return "ne";
	case QLocale::Language::NorwegianBokmal:
		return "nb";
	case QLocale::Language::NorwegianNynorsk:
		return "nn";
	case QLocale::Language::Occitan:
		return "oc";
	case QLocale::Language::Oriya:
		return "or";
	case QLocale::Language::Persian:
		return "fa";
	case QLocale::Language::Polish:
		return "pl";
	case QLocale::Language::Portuguese:
		return "pt";
	case QLocale::Language::Quechua:
		return "qu";
	case QLocale::Language::Romanian:
		return "ro";
	case QLocale::Language::Russian:
		return "ru";
	case QLocale::Language::Samoan:
		return "sm";
	case QLocale::Language::Sanskrit:
		return "sa";
	case QLocale::Language::Serbian:
		return "sr";
	case QLocale::Language::Shona:
		return "sn";
	case QLocale::Language::Slovak:
		return "sk";
	case QLocale::Language::Slovenian:
		return "sl";
	case QLocale::Language::Somali:
		return "so";
	case QLocale::Language::Spanish:
		return "es";
	case QLocale::Language::Sundanese:
		return "su";
	case QLocale::Language::Swahili:
		return "sw";
	case QLocale::Language::Swedish:
		return "sv";
	case QLocale::Language::Tagalog:
		return "tl";
	case QLocale::Language::Tajik:
		return "tg";
	case QLocale::Language::Tamil:
		return "ta";
	case QLocale::Language::Tatar:
		return "tt";
	case QLocale::Language::Telugu:
		return "te";
	case QLocale::Language::Thai:
		return "th";
	case QLocale::Language::Tibetan:
		return "bo";
	case QLocale::Language::Tigrinya:
		return "ti";
	case QLocale::Language::Tsonga:
		return "ts";
	case QLocale::Language::Turkish:
		return "tr";
	case QLocale::Language::Turkmen:
		return "tk";
	case QLocale::Language::Uigur:
		return "ug";
	case QLocale::Language::Ukrainian:
		return "uk";
	case QLocale::Language::Urdu:
		return "ur";
	case QLocale::Language::Uzbek:
		return "uz";
	case QLocale::Language::Vietnamese:
		return "vi";
	case QLocale::Language::Volapuk:
		return "vo";
	case QLocale::Language::Welsh:
		return "cy";
	case QLocale::Language::Wolof:
		return "wo";
	case QLocale::Language::Xhosa:
		return "xh";
	case QLocale::Language::Yiddish:
		return "yi";
	case QLocale::Language::Yoruba:
		return "yo";
	case QLocale::Language::Zhuang:
		return "za";
	case QLocale::Language::Zulu:
		return "zu";
	case QLocale::Language::Manx:
		return "gv";
	case QLocale::Language::Igbo:
		return "ig";
	case QLocale::Language::Venda:
		return "ve";
	case QLocale::Language::Ewe:
		return "ee";
	case QLocale::Language::Chewa:
		return "ny";
	case QLocale::Language::Fulah:
		return "ff";
	case QLocale::Language::Kikuyu:
		return "ki";
	case QLocale::Language::Bambara:
		return "bm";

	default:
		return QString();
	}
}

/*!
 * This function returns the ISO 3166-1 alpha-2 country code for the given
 * QLocale's country() property. If the country property value is not
 * supported, then a default-constructed QString will be returned instead.
 *
 * For more information, see:
 *
 *     https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
 *
 * \param locale The locale object to inspect.
 * \return The ISO 3166-1 alpha-2 country code for the locale's country.
 */
QString getLocaleCountryCode(const QLocale &locale)
{
	switch(locale.country())
	{
	case QLocale::Country::Afghanistan:
		return "AF";
	case QLocale::Country::Albania:
		return "AL";
	case QLocale::Country::Algeria:
		return "DZ";
	case QLocale::Country::AmericanSamoa:
		return "AS";
	case QLocale::Country::Andorra:
		return "AD";
	case QLocale::Country::Angola:
		return "AO";
	case QLocale::Country::Anguilla:
		return "AI";
	case QLocale::Country::Antarctica:
		return "AQ";
	case QLocale::Country::AntiguaAndBarbuda:
		return "AG";
	case QLocale::Country::Argentina:
		return "AR";
	case QLocale::Country::Armenia:
		return "AM";
	case QLocale::Country::Aruba:
		return "AW";
	case QLocale::Country::Australia:
		return "AU";
	case QLocale::Country::Austria:
		return "AT";
	case QLocale::Country::Azerbaijan:
		return "AZ";
	case QLocale::Country::Bahamas:
		return "BS";
	case QLocale::Country::Bahrain:
		return "BH";
	case QLocale::Country::Bangladesh:
		return "BD";
	case QLocale::Country::Barbados:
		return "BB";
	case QLocale::Country::Belarus:
		return "BY";
	case QLocale::Country::Belgium:
		return "BE";
	case QLocale::Country::Belize:
		return "BZ";
	case QLocale::Country::Benin:
		return "BJ";
	case QLocale::Country::Bermuda:
		return "BM";
	case QLocale::Country::Bhutan:
		return "BT";
	case QLocale::Country::Bolivia:
		return "BO";
	case QLocale::Country::BosniaAndHerzegowina:
		return "BA";
	case QLocale::Country::Botswana:
		return "BW";
	case QLocale::Country::BouvetIsland:
		return "BV";
	case QLocale::Country::Brazil:
		return "BR";
	case QLocale::Country::BritishIndianOceanTerritory:
		return "IO";
	case QLocale::Country::Bulgaria:
		return "BG";
	case QLocale::Country::BurkinaFaso:
		return "BF";
	case QLocale::Country::Burundi:
		return "BI";
	case QLocale::Country::Cambodia:
		return "KH";
	case QLocale::Country::Cameroon:
		return "CM";
	case QLocale::Country::Canada:
		return "CA";
	case QLocale::Country::CaymanIslands:
		return "KY";
	case QLocale::Country::CentralAfricanRepublic:
		return "CF";
	case QLocale::Country::Chad:
		return "TD";
	case QLocale::Country::Chile:
		return "CL";
	case QLocale::Country::China:
		return "CN";
	case QLocale::Country::ChristmasIsland:
		return "CX";
	case QLocale::Country::CocosIslands:
		return "CC";
	case QLocale::Country::Colombia:
		return "CO";
	case QLocale::Country::Comoros:
		return "KM";

	case QLocale::Country::DemocraticRepublicOfCongo:
	case QLocale::Country::PeoplesRepublicOfCongo:
		return "CD";

	case QLocale::Country::CookIslands:
		return "CK";
	case QLocale::Country::CostaRica:
		return "CR";
	case QLocale::Country::IvoryCoast:
		return "CI";
	case QLocale::Country::Croatia:
		return "HR";
	case QLocale::Country::Cuba:
		return "CU";
	case QLocale::Country::Cyprus:
		return "CY";
	case QLocale::Country::CzechRepublic:
		return "CZ";
	case QLocale::Country::Denmark:
		return "DK";
	case QLocale::Country::Djibouti:
		return "DJ";
	case QLocale::Country::Dominica:
		return "DM";
	case QLocale::Country::DominicanRepublic:
		return "DO";
	case QLocale::Country::EastTimor:
		return "TL";
	case QLocale::Country::Ecuador:
		return "EC";
	case QLocale::Country::Egypt:
		return "EG";
	case QLocale::Country::ElSalvador:
		return "SV";
	case QLocale::Country::EquatorialGuinea:
		return "GQ";
	case QLocale::Country::Eritrea:
		return "ER";
	case QLocale::Country::Estonia:
		return "EE";
	case QLocale::Country::Ethiopia:
		return "ET";
	case QLocale::Country::FalklandIslands:
		return "FK";
	case QLocale::Country::FaroeIslands:
		return "FO";
	case QLocale::Country::Finland:
		return "FI";
	case QLocale::Country::France:
		return "FR";
	case QLocale::Country::FrenchGuiana:
		return "GF";
	case QLocale::Country::FrenchPolynesia:
		return "PF";
	case QLocale::Country::FrenchSouthernTerritories:
		return "TF";
	case QLocale::Country::Gabon:
		return "GA";
	case QLocale::Country::Gambia:
		return "GM";
	case QLocale::Country::Georgia:
		return "GE";
	case QLocale::Country::Germany:
		return "DE";
	case QLocale::Country::Ghana:
		return "GH";
	case QLocale::Country::Gibraltar:
		return "GI";
	case QLocale::Country::Greece:
		return "GR";
	case QLocale::Country::Greenland:
		return "GL";
	case QLocale::Country::Grenada:
		return "GD";
	case QLocale::Country::Guadeloupe:
		return "GP";
	case QLocale::Country::Guam:
		return "GU";
	case QLocale::Country::Guatemala:
		return "GT";
	case QLocale::Country::Guinea:
		return "GN";
	case QLocale::Country::GuineaBissau:
		return "GW";
	case QLocale::Country::Guyana:
		return "GY";
	case QLocale::Country::Haiti:
		return "HT";
	case QLocale::Country::HeardAndMcDonaldIslands:
		return "HM";
	case QLocale::Country::Honduras:
		return "HN";
	case QLocale::Country::HongKong:
		return "HK";
	case QLocale::Country::Hungary:
		return "HU";
	case QLocale::Country::Iceland:
		return "IS";
	case QLocale::Country::India:
		return "IN";
	case QLocale::Country::Indonesia:
		return "ID";
	case QLocale::Country::Iran:
		return "IR";
	case QLocale::Country::Iraq:
		return "IQ";
	case QLocale::Country::Ireland:
		return "IE";
	case QLocale::Country::Israel:
		return "IL";
	case QLocale::Country::Italy:
		return "IT";
	case QLocale::Country::Jamaica:
		return "JM";
	case QLocale::Country::Japan:
		return "JP";
	case QLocale::Country::Jordan:
		return "JO";
	case QLocale::Country::Kazakhstan:
		return "KZ";
	case QLocale::Country::Kenya:
		return "KE";
	case QLocale::Country::Kiribati:
		return "KI";
	case QLocale::Country::DemocraticRepublicOfKorea:
		return "KP";
	case QLocale::Country::RepublicOfKorea:
		return "KR";
	case QLocale::Country::Kuwait:
		return "KW";
	case QLocale::Country::Kyrgyzstan:
		return "KG";
	case QLocale::Country::Latvia:
		return "LV";
	case QLocale::Country::Lebanon:
		return "LB";
	case QLocale::Country::Lesotho:
		return "LS";
	case QLocale::Country::Liberia:
		return "LR";
	case QLocale::Country::Liechtenstein:
		return "LI";
	case QLocale::Country::Lithuania:
		return "LT";
	case QLocale::Country::Luxembourg:
		return "LU";
	case QLocale::Country::Macau:
		return "MO";
	case QLocale::Country::Macedonia:
		return "MK";
	case QLocale::Country::Madagascar:
		return "MG";
	case QLocale::Country::Malawi:
		return "MW";
	case QLocale::Country::Malaysia:
		return "MY";
	case QLocale::Country::Maldives:
		return "MV";
	case QLocale::Country::Mali:
		return "ML";
	case QLocale::Country::Malta:
		return "MT";
	case QLocale::Country::MarshallIslands:
		return "MH";
	case QLocale::Country::Martinique:
		return "MQ";
	case QLocale::Country::Mauritania:
		return "MR";
	case QLocale::Country::Mauritius:
		return "MU";
	case QLocale::Country::Mayotte:
		return "YT";
	case QLocale::Country::Mexico:
		return "MX";
	case QLocale::Country::Micronesia:
		return "FM";
	case QLocale::Country::Monaco:
		return "MC";
	case QLocale::Country::Mongolia:
		return "MN";
	case QLocale::Country::Montserrat:
		return "MS";
	case QLocale::Country::Morocco:
		return "MA";
	case QLocale::Country::Mozambique:
		return "MZ";
	case QLocale::Country::Myanmar:
		return "MM";
	case QLocale::Country::Namibia:
		return "NA";
	case QLocale::Country::NauruCountry:
		return "NR";
	case QLocale::Country::Nepal:
		return "NP";
	case QLocale::Country::Netherlands:
		return "NL";
	case QLocale::Country::NewCaledonia:
		return "NC";
	case QLocale::Country::NewZealand:
		return "NZ";
	case QLocale::Country::Nicaragua:
		return "NI";
	case QLocale::Country::Niger:
		return "NE";
	case QLocale::Country::Nigeria:
		return "NG";
	case QLocale::Country::Niue:
		return "NU";
	case QLocale::Country::NorfolkIsland:
		return "NF";
	case QLocale::Country::NorthernMarianaIslands:
		return "MP";
	case QLocale::Country::Norway:
		return "NO";
	case QLocale::Country::Oman:
		return "OM";
	case QLocale::Country::Pakistan:
		return "PK";
	case QLocale::Country::Palau:
		return "PW";
	case QLocale::Country::Panama:
		return "PA";
	case QLocale::Country::PapuaNewGuinea:
		return "PG";
	case QLocale::Country::Paraguay:
		return "PY";
	case QLocale::Country::Peru:
		return "PE";
	case QLocale::Country::Philippines:
		return "PH";
	case QLocale::Country::Pitcairn:
		return "PN";
	case QLocale::Country::Poland:
		return "PL";
	case QLocale::Country::Portugal:
		return "PT";
	case QLocale::Country::PuertoRico:
		return "PR";
	case QLocale::Country::Qatar:
		return "QA";
	case QLocale::Country::Reunion:
		return "RE";
	case QLocale::Country::Romania:
		return "RO";
	case QLocale::Country::RussianFederation:
		return "RU";
	case QLocale::Country::Rwanda:
		return "RW";
	case QLocale::Country::SaintKittsAndNevis:
		return "KN";
	case QLocale::Country::Samoa:
		return "WS";
	case QLocale::Country::SanMarino:
		return "SM";
	case QLocale::Country::SaoTomeAndPrincipe:
		return "ST";
	case QLocale::Country::SaudiArabia:
		return "SA";
	case QLocale::Country::Senegal:
		return "SN";
	case QLocale::Country::Seychelles:
		return "SC";
	case QLocale::Country::SierraLeone:
		return "SL";
	case QLocale::Country::Singapore:
		return "SG";
	case QLocale::Country::Slovakia:
		return "SK";
	case QLocale::Country::Slovenia:
		return "SI";
	case QLocale::Country::SolomonIslands:
		return "SB";
	case QLocale::Country::Somalia:
		return "SO";
	case QLocale::Country::SouthAfrica:
		return "ZA";
	case QLocale::Country::SouthGeorgiaAndTheSouthSandwichIslands:
		return "GS";
	case QLocale::Country::Spain:
		return "ES";
	case QLocale::Country::SriLanka:
		return "LK";
	case QLocale::Country::Sudan:
		return "SD";
	case QLocale::Country::Suriname:
		return "SR";
	case QLocale::Country::SvalbardAndJanMayenIslands:
		return "SJ";
	case QLocale::Country::Swaziland:
		return "SZ";
	case QLocale::Country::Sweden:
		return "SE";
	case QLocale::Country::Switzerland:
		return "CH";
	case QLocale::Country::SyrianArabRepublic:
		return "SY";
	case QLocale::Country::Taiwan:
		return "TW";
	case QLocale::Country::Tajikistan:
		return "TJ";
	case QLocale::Country::Tanzania:
		return "TZ";
	case QLocale::Country::Thailand:
		return "TH";
	case QLocale::Country::Togo:
		return "TG";
	case QLocale::Country::Tokelau:
		return "TK";
	case QLocale::Country::TrinidadAndTobago:
		return "TT";
	case QLocale::Country::Tunisia:
		return "TN";
	case QLocale::Country::Turkey:
		return "TR";
	case QLocale::Country::Turkmenistan:
		return "TM";
	case QLocale::Country::TurksAndCaicosIslands:
		return "TC";
	case QLocale::Country::Tuvalu:
		return "TV";
	case QLocale::Country::Uganda:
		return "UG";
	case QLocale::Country::Ukraine:
		return "UA";
	case QLocale::Country::UnitedArabEmirates:
		return "AE";
	case QLocale::Country::UnitedKingdom:
		return "GB";

	case QLocale::Country::UnitedStates:
	case QLocale::Country::AnyCountry:
		return "US";

	case QLocale::Country::UnitedStatesMinorOutlyingIslands:
		return "UM";
	case QLocale::Country::Uruguay:
		return "UY";
	case QLocale::Country::Uzbekistan:
		return "UZ";
	case QLocale::Country::Vanuatu:
		return "VU";
	case QLocale::Country::VaticanCityState:
		return "VA";
	case QLocale::Country::Venezuela:
		return "VE";
	case QLocale::Country::BritishVirginIslands:
		return "VG";
	case QLocale::Country::WallisAndFutunaIslands:
		return "WF";
	case QLocale::Country::WesternSahara:
		return "EH";
	case QLocale::Country::Yemen:
		return "YE";
	case QLocale::Country::Zambia:
		return "ZM";
	case QLocale::Country::Zimbabwe:
		return "ZW";
	case QLocale::Country::Montenegro:
		return "ME";
	case QLocale::Country::Serbia:
		return "RS";
	case QLocale::Country::SaintBarthelemy:
		return "BL";
	case QLocale::Country::SaintMartin:
		return "MF";

	default:
		return QString();
	}
}
}
}
