language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.2.3-Linux-x86_64/* /usr/
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu utopic main"
  - sudo apt-get update -qq
  - sudo apt-get install -y --quiet gcc-4.9 g++-4.9
  - export CC="/usr/bin/gcc-4.9"
  - export CXX="/usr/bin/g++-4.9"
  - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
  - sudo apt-get install -y --quiet ttf-mscorefonts-installer
  - sudo apt-get install -y --quiet x-ttcidfont-conf
  - fc-cache -fv
  - sudo apt-get install -y --quiet libhunspell-dev
  - sudo apt-get install -y --quiet libboost-dev
  - sudo apt-get install -y --quiet libicu-dev
  - sudo apt-get install -y --quiet qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev qtbase5-dev libqt5gui5 libqt5printsupport5 libqt5widgets5 libqt5network5

install:
  - wget https://github.com/libgit2/libgit2/archive/v0.22.2.tar.gz -O libgit2-0.22.2.tar.gz
  - tar -xzf libgit2-0.22.2.tar.gz
  - cd libgit2-0.22.2
  - mkdir build
  - cd build
  - cmake .. -DBUILD_CLAR=OFF
  - make
  - sudo make install
  - cd ../../

before_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./src/QomposeTest/QomposeTest
